// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPaQDKsyAqs8sRN_iMTOLI9T9lQ_ZvJG8',
    appId: '1:11878560776:web:8bce6bce6bc5860eaccdbd',
    messagingSenderId: '11878560776',
    projectId: 'kasir-sederhana-6b35a',
    authDomain: 'kasir-sederhana-6b35a.firebaseapp.com',
    storageBucket: 'kasir-sederhana-6b35a.firebasestorage.app',
    measurementId: 'G-XNC86EXRG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeKMBR2sUYFfN49-k6SaObO_po1_XkHMA',
    appId: '1:11878560776:android:7d109e20d3f6d9e3accdbd',
    messagingSenderId: '11878560776',
    projectId: 'kasir-sederhana-6b35a',
    storageBucket: 'kasir-sederhana-6b35a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnkS0ALHadFo68DrTuTd-b5EZEJoDmWGs',
    appId: '1:11878560776:ios:b2799ea3e44605e5accdbd',
    messagingSenderId: '11878560776',
    projectId: 'kasir-sederhana-6b35a',
    storageBucket: 'kasir-sederhana-6b35a.firebasestorage.app',
    iosBundleId: 'com.example.kasirSederhana',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnkS0ALHadFo68DrTuTd-b5EZEJoDmWGs',
    appId: '1:11878560776:ios:b2799ea3e44605e5accdbd',
    messagingSenderId: '11878560776',
    projectId: 'kasir-sederhana-6b35a',
    storageBucket: 'kasir-sederhana-6b35a.firebasestorage.app',
    iosBundleId: 'com.example.kasirSederhana',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPaQDKsyAqs8sRN_iMTOLI9T9lQ_ZvJG8',
    appId: '1:11878560776:web:c400503aa645df4eaccdbd',
    messagingSenderId: '11878560776',
    projectId: 'kasir-sederhana-6b35a',
    authDomain: 'kasir-sederhana-6b35a.firebaseapp.com',
    storageBucket: 'kasir-sederhana-6b35a.firebasestorage.app',
    measurementId: 'G-DNNZ7SLL6F',
  );

}